/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ServiceProvider, LocationCoordinates } from './types';

// Anchor point: "Downtown Hub"
export const PRESET_LOCATIONS: LocationCoordinates[] = [
  {
    name: "Downtown Financial Core",
    latitude: 43.6487,
    longitude: -79.3817
  },
  {
    name: "University Medical District",
    latitude: 43.6592,
    longitude: -79.3908
  },
  {
    name: "Queens Quay Harbour",
    latitude: 43.6384,
    longitude: -79.3820
  },
  {
    name: "High Park Residential",
    latitude: 43.6465,
    longitude: -79.4633
  }
];

export const INITIAL_SERVICES: ServiceProvider[] = [
  {
    id: "hosp-1",
    name: "Metro General Emergency & Trauma",
    category: "hospital",
    crowdLevel: "high",
    isOpen: true,
    rating: 4.8,
    latitude: 43.6515,
    longitude: -79.3855,
    address: "150 University Ave, Toronto",
    phone: "+1 (555) 123-4567",
    hasDelivery: false,
    hasHomeService: true, // Emergency ambulance triage
    estimatedWaitTime: 95,
    ownerId: null,
    description: "Main city trauma center dealing with high emergency load. Immediate care for life-threatening issues, but check for urgent cares for general ailments.",
    servicesOffered: ["Level 1 Trauma Triage", "Emergency Surgery", "ICU Care", "Pediatric ER", "24/7 Diagnostics"]
  },
  {
    id: "hosp-2",
    name: "Bloor West Urgent Care Clinic",
    category: "hospital",
    crowdLevel: "low",
    isOpen: true,
    rating: 4.4,
    latitude: 43.6570,
    longitude: -79.3930,
    address: "620 Bloor St W, Toronto",
    phone: "+1 (555) 765-4321",
    hasDelivery: false,
    hasHomeService: true, // Urgent mobile clinic
    estimatedWaitTime: 12,
    ownerId: "provider-demo-1", // Managed by default provider login
    description: "Multi-disciplinary physical medicine and family physician clinic. Excel in fast-track sutures, minor bone fractures, and diagnostic checkups.",
    servicesOffered: ["Stitching & Casts", "Flu Vaccines", "Minor Fracture Triage", "Family Care", "Lab Services"]
  },
  {
    id: "hosp-3",
    name: "St. Luke's Specialist Ward",
    category: "hospital",
    crowdLevel: "medium",
    isOpen: true,
    rating: 4.6,
    latitude: 43.6420,
    longitude: -79.3750,
    address: "240 King St E, Toronto",
    phone: "+1 (555) 987-6543",
    hasDelivery: false,
    hasHomeService: false,
    estimatedWaitTime: 40,
    ownerId: null,
    description: "Specialized outpatient center. Known for high comfort and specialized clinics but slightly slower scheduling than community clinics.",
    servicesOffered: ["Cardiology Tests", "Orthopedic consults", "Dermatology Clinic", "X-Ray imaging"]
  },
  {
    id: "bank-1",
    name: "Apex Trust Financial Center",
    category: "bank",
    crowdLevel: "high",
    isOpen: true,
    rating: 4.1,
    latitude: 43.6480,
    longitude: -79.3800,
    address: "100 King St W, Toronto",
    phone: "+1 (555) 345-6789",
    hasDelivery: false,
    hasHomeService: true, // Premium notary home services
    estimatedWaitTime: 50,
    ownerId: null,
    description: "Corporate flagship bank hub. Extremely high pedestrian volume at midday due to commercial business accounting activities.",
    servicesOffered: ["Corporate Depositories", "Safe Locker Units", "Mortgage Advising", "Foreign Exchange Counter"]
  },
  {
    id: "bank-2",
    name: "Horizon Credit Union",
    category: "bank",
    crowdLevel: "low",
    isOpen: true,
    rating: 4.5,
    latitude: 43.6530,
    longitude: -79.3710,
    address: "442 Parliament St, Toronto",
    phone: "+1 (555) 890-1234",
    hasDelivery: false,
    hasHomeService: true, // Mobile wealth advisory
    estimatedWaitTime: 4,
    ownerId: null,
    description: "Community credit union with advanced digital terminals. Quick human teller access and zero wait lines on average weekdays.",
    servicesOffered: ["Personal Banking", "Debit Card Dispatch", "Small Business Loans", "Senior Accounts Portal"]
  },
  {
    id: "bank-3",
    name: "Pinnacle Merchant Bankers",
    category: "bank",
    crowdLevel: "medium",
    isOpen: false, // Closed right now
    rating: 3.9,
    latitude: 43.6460,
    longitude: -79.3950,
    address: "510 Spadina Ave, Toronto",
    phone: "+1 (555) 234-5678",
    hasDelivery: false,
    hasHomeService: false,
    estimatedWaitTime: 22,
    ownerId: null,
    description: "Main branch with focus on commercial merchant POS setups. High average queues during business mornings.",
    servicesOffered: ["Merchant Terminals Support", "Corporate Lines of Credit", "Forex Tellers"]
  },
  {
    id: "shop-1",
    name: "Central Supermarket",
    category: "shop",
    crowdLevel: "high",
    isOpen: true,
    rating: 4.3,
    latitude: 43.6450,
    longitude: -79.3830,
    address: "120 Bay St, Toronto",
    phone: "+1 (555) 876-5432",
    hasDelivery: true, // Home groceries dispatch
    hasHomeService: false,
    estimatedWaitTime: 35,
    ownerId: null,
    description: "Largest core grocery mart. High crowding near cashier lanes. Order online for contactless delivery or pick optimal off-peak hours.",
    servicesOffered: ["Organic Produce", "Fresh Delicatessen", "Bakery Rack", "Prescription Counter", "Curb-side Dispatch"]
  },
  {
    id: "shop-2",
    name: "Spadina Health & Wellness Pharmacy",
    category: "shop",
    crowdLevel: "low",
    isOpen: true,
    rating: 4.7,
    latitude: 43.6590,
    longitude: -79.3980,
    address: "311 Spadina Ave, Toronto",
    phone: "+1 (555) 543-2109",
    hasDelivery: true, // Real-time prescription drops
    hasHomeService: true, // In-home medication setup
    estimatedWaitTime: 3,
    ownerId: "provider-demo-2", // Managed by demo-pharmacy provider
    description: "Local independent compounding healthcare pharmacy and boutique health shop. High touch patient care with swift triage setup.",
    servicesOffered: ["Compounding Medicine", "Vaccine Injections", "Assisted Senior Care Packs", "Same-day Courier Delivery"]
  },
  {
    id: "shop-3",
    name: "Metro Grocers Outlet",
    category: "shop",
    crowdLevel: "medium",
    isOpen: true,
    rating: 4.2,
    latitude: 43.6550,
    longitude: -79.3800,
    address: "21 Dundas Square, Toronto",
    phone: "+1 (555) 111-2222",
    hasDelivery: true,
    hasHomeService: false,
    estimatedWaitTime: 18,
    ownerId: null,
    description: "Express format grocery store situated in Dundas Square. High self-checkout terminal density ensures queue motion is steady.",
    servicesOffered: ["Fresh Groceries", "Halal Counters", "Express Hot Meals Bar", "Mobile Wallet Tills"]
  },
  {
    id: "hotel-1",
    name: "The Ritz-Carlton Waterfront",
    category: "hotel",
    crowdLevel: "medium",
    isOpen: true,
    rating: 4.9,
    latitude: 43.6425,
    longitude: -79.3875,
    address: "181 Wellington St W, Toronto",
    phone: "+1 (555) 555-0100",
    hasDelivery: false,
    hasHomeService: true,
    estimatedWaitTime: 15,
    ownerId: null,
    description: "Ultra-luxury hotel overlooking the city harbor. Offers smooth standard checks, baggage screening triage, and priority valet queues.",
    servicesOffered: ["Executive Suites", "Spa Triage & Recovery", "Priority Boarding Lounge", "Waterfront Fine Dining"]
  },
  {
    id: "hotel-2",
    name: "Harbourfront Suites & Lodge",
    category: "hotel",
    crowdLevel: "low",
    isOpen: true,
    rating: 4.5,
    latitude: 43.6390,
    longitude: -79.3810,
    address: "350 Queens Quay W, Toronto",
    phone: "+1 (555) 555-0200",
    hasDelivery: true,
    hasHomeService: true,
    estimatedWaitTime: 5,
    ownerId: null,
    description: "Premium lakeside suites with interactive concierge panels. Exceptionally short desk waits and automated card keys dispatch.",
    servicesOffered: ["Lakeside Balcony Rooms", "Room Service Dispatch", "Heated Pool Access", "Fast Key Card Triage"]
  },
  {
    id: "lodge-1",
    name: "Downtown Travelers Lodge",
    category: "lodge",
    crowdLevel: "low",
    isOpen: true,
    rating: 4.2,
    latitude: 43.6495,
    longitude: -79.3780,
    address: "220 Yonge St, Toronto",
    phone: "+1 (555) 555-0300",
    hasDelivery: false,
    hasHomeService: true,
    estimatedWaitTime: 8,
    ownerId: null,
    description: "Affordable backpacker style lodgings with compact study rooms. Highly responsive check-in line management during transit hours.",
    servicesOffered: ["Express Shared Pods", "Co-working Desks", "Free Fiber Internet", "Laundry Dispatch Room"]
  },
  {
    id: "lodge-2",
    name: "Queens Quay Cabin Lodge",
    category: "lodge",
    crowdLevel: "high",
    isOpen: true,
    rating: 4.3,
    latitude: 43.6375,
    longitude: -79.3840,
    address: "700 Queens Quay, Toronto",
    phone: "+1 (555) 555-0400",
    hasDelivery: false,
    hasHomeService: false,
    estimatedWaitTime: 30,
    ownerId: null,
    description: "Rustic cottage lodges near the marine channel. Highly crowded on weekends due to tourist check-ins; digital registration advised.",
    servicesOffered: ["Individual Pine Cabins", "Private Marine Slides", "Campfires Triage", "Sailboat Parking Spot"]
  },
  {
    id: "market-1",
    name: "Harbourfront Farmers Market",
    category: "market",
    crowdLevel: "medium",
    isOpen: true,
    rating: 4.7,
    latitude: 43.6385,
    longitude: -79.3822,
    address: "235 Queens Quay W, Toronto",
    phone: "+1 (555) 555-0500",
    hasDelivery: true,
    hasHomeService: false,
    estimatedWaitTime: 10,
    ownerId: null,
    description: "Open-air organic food vendor market directly at the harbor docks. Lively street food counters and moderate lines.",
    servicesOffered: ["Local Organic Farming", "Artisanal Cheese Rack", "Live Music Stand", "Vegan Pastry Corners"]
  },
  {
    id: "market-2",
    name: "St. Lawrence Artisan Market",
    category: "market",
    crowdLevel: "high",
    isOpen: true,
    rating: 4.8,
    latitude: 43.6490,
    longitude: -79.3715,
    address: "93 Front St E, Toronto",
    phone: "+1 (555) 555-0600",
    hasDelivery: false,
    hasHomeService: false,
    estimatedWaitTime: 40,
    ownerId: null,
    description: "Historic city market featuring high-congestion delis and craft counters. Use the SmartTriage queue tickets to bypass weekend lines.",
    servicesOffered: ["World Famous Peameal Bacon", "Handmade Leather Goods", "Seafood Imports", "Antiques Triage Hall"]
  },
  {
    id: "supermarket-1",
    name: "Loblaws Waterfront Supermarket",
    category: "supermarket",
    crowdLevel: "medium",
    isOpen: true,
    rating: 4.6,
    latitude: 43.6398,
    longitude: -79.3805,
    address: "10 Lower Jarvis St, Toronto",
    phone: "+1 (555) 555-0700",
    hasDelivery: true,
    hasHomeService: false,
    estimatedWaitTime: 20,
    ownerId: null,
    description: "Massive scale grocery and supermarket outlet with full pharmacy desk and fresh bakery department.",
    servicesOffered: ["Prime Cut Meat Bar", "Pharmacy Compounding Desk", "Self-Checkout Hub", "Curb side Delivery Spot"]
  },
  {
    id: "supermarket-2",
    name: "Financial District Fine Foods",
    category: "supermarket",
    crowdLevel: "low",
    isOpen: true,
    rating: 4.4,
    latitude: 43.6472,
    longitude: -79.3828,
    address: "200 Bay St, Toronto",
    phone: "+1 (555) 555-0800",
    hasDelivery: true,
    hasHomeService: false,
    estimatedWaitTime: 6,
    ownerId: null,
    description: "Elite level grocery mart offering imported delicacies. Compact lines, swift lanes, and excellent wait optimization.",
    servicesOffered: ["Organic Coldpressed Juices", "Premium Sushi Triage", "Eco Bag Dispatch", "Gourmet Coffee Bar"]
  },
  {
    id: "hosp-4",
    name: "Waterfront Immediate Care Hospital",
    category: "hospital",
    crowdLevel: "low",
    isOpen: true,
    rating: 4.8,
    latitude: 43.6380,
    longitude: -79.3830,
    address: "20 Queens Quay W, Toronto",
    phone: "+1 (555) 555-0900",
    hasDelivery: false,
    hasHomeService: true,
    estimatedWaitTime: 10,
    ownerId: null,
    description: "State of the art urgent care clinic specialized in rapid patient diagnostics. Minimal congestion, low wait loads.",
    servicesOffered: ["X-Ray & Trauma Scan", "Emergency Pediatrics", "Flu & Vaccination Shots", "Ambulance Priority Air"]
  },
  {
    id: "bank-4",
    name: "Queens Quay Community Savings",
    category: "bank",
    crowdLevel: "low",
    isOpen: true,
    rating: 4.6,
    latitude: 43.6388,
    longitude: -79.3812,
    address: "410 Queens Quay W, Toronto",
    phone: "+1 (555) 555-1000",
    hasDelivery: false,
    hasHomeService: true,
    estimatedWaitTime: 4,
    ownerId: null,
    description: "Local community-led savings branch. Low teller lines and quick personal loan and wealth consultation.",
    servicesOffered: ["Personal Banking", "Debit Card Quick Dispense", "Mortgage Triage Advisors", "Foreign Cash Reserves"]
  },
  {
    id: "hostel-1",
    name: "High Park Youth Hostel",
    category: "hostel",
    crowdLevel: "medium",
    isOpen: true,
    rating: 4.4,
    latitude: 43.6470,
    longitude: -79.4590,
    address: "1860 Bloor St W, Toronto",
    phone: "+1 (555) 555-2010",
    hasDelivery: false,
    hasHomeService: true,
    estimatedWaitTime: 12,
    ownerId: null,
    description: "Vibrant community hostel with shared double bunks, direct access to subway lines, and secure lockers.",
    servicesOffered: ["Shared Dorm beds", "Free Breakfast", "Secure Lockers", "Baggage Storage Space"]
  },
  {
    id: "hostel-2",
    name: "Downtown Backpackers Hostel",
    category: "hostel",
    crowdLevel: "low",
    isOpen: true,
    rating: 4.1,
    latitude: 43.6510,
    longitude: -79.3790,
    address: "45 Church St, Toronto",
    phone: "+1 (555) 555-2020",
    hasDelivery: false,
    hasHomeService: true,
    estimatedWaitTime: 4,
    ownerId: null,
    description: "Low crowding, automated touchless check-in pods. Highly clean and modern facilities near the financial core.",
    servicesOffered: ["Capsule Bed Units", "Laundry Access", "24/7 Security Desk", "Kitchen privilege"]
  },
  {
    id: "hostel-3",
    name: "University Campus Hostel",
    category: "hostel",
    crowdLevel: "high",
    isOpen: true,
    rating: 4.2,
    latitude: 43.6580,
    longitude: -79.3920,
    address: "80 St George St, Toronto",
    phone: "+1 (555) 555-2030",
    hasDelivery: false,
    hasHomeService: false,
    estimatedWaitTime: 45,
    ownerId: null,
    description: "Undergrad study lodge and hostel. Highly crowded checkout counters and high peak queues on study terms.",
    servicesOffered: ["Student Single Rooms", "Co-work Space", "Study Triage Desk", "Highspeed Campus WiFi"]
  },
  {
    id: "xerox-1",
    name: "Metro Print & Xerox Express",
    category: "xerox_shop",
    crowdLevel: "low",
    isOpen: true,
    rating: 4.7,
    latitude: 43.6492,
    longitude: -79.3812,
    address: "120 King St W, Toronto",
    phone: "+1 (555) 555-3010",
    hasDelivery: true,
    hasHomeService: true,
    estimatedWaitTime: 2,
    ownerId: null,
    description: "Premium laser xerox and binding boutique. Zero lines, extremely fast dual-nozzle copy runs.",
    servicesOffered: ["Color Xerox Duplicating", "Spiral Binding", "Laminating Triage", "Document scanning"]
  },
  {
    id: "xerox-2",
    name: "Spadina Copier & Xerox Hub",
    category: "xerox_shop",
    crowdLevel: "high",
    isOpen: true,
    rating: 4.3,
    latitude: 43.6585,
    longitude: -79.3985,
    address: "351 Spadina Ave, Toronto",
    phone: "+1 (555) 555-3020",
    hasDelivery: false,
    hasHomeService: false,
    estimatedWaitTime: 32,
    ownerId: null,
    description: "Highly busy student copy shop. Packed during assignment hand-in cycles; check wait index before queueing.",
    servicesOffered: ["Massive Volume Copying", "Thesis Binding", "Poster Print Plots", "ID Photo printing"]
  },
  {
    id: "xerox-3",
    name: "QuickDoc Xerox & Print Shop",
    category: "xerox_shop",
    crowdLevel: "medium",
    isOpen: true,
    rating: 4.5,
    latitude: 43.6415,
    longitude: -79.3825,
    address: "207 Queens Quay W, Toronto",
    phone: "+1 (555) 555-3030",
    hasDelivery: true,
    hasHomeService: false,
    estimatedWaitTime: 10,
    ownerId: null,
    description: "Waterside local printer. Moderate load, friendly service, high accuracy copying.",
    servicesOffered: ["High Speed PDF print", "Standard B&W Xerox", "Cardboard package packing", "Brochure folding"]
  },
  {
    id: "general-1",
    name: "Queens Quay General Services Clinic",
    category: "general",
    crowdLevel: "low",
    isOpen: true,
    rating: 4.6,
    latitude: 43.6382,
    longitude: -79.3815,
    address: "508 Queens Quay W, Toronto",
    phone: "+1 (555) 555-4010",
    hasDelivery: true,
    hasHomeService: true,
    estimatedWaitTime: 3,
    ownerId: null,
    description: "All-in-one general municipal administrative desk, luggage check, and priority notary dispatch.",
    servicesOffered: ["Municipal forms filing", "Baggage scale triage", "Notary stamp line", "Public terminal access"]
  }
];

// Helper formula to compute great-circle distance between two coordinates in kilometers (Haversine formula)
export function getDistanceInKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371; // Radius of earth in km
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a = 
    Math.sin(dLat/2) * Math.sin(dLat/2) +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * 
    Math.sin(dLon/2) * Math.sin(dLon/2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
  const d = R * c;
  return Math.round(d * 10) / 10; // Round to 1 decimal place
}
